"""L0+L1 快速冒烟测试 — 不依赖 LLM API 调用，不修改任何源码"""
import sys; sys.path.insert(0, ".")
import re

FAILS = 0

def check(name, condition, detail=""):
    global FAILS
    if condition:
        print(f"  ✅ {name}")
    else:
        FAILS += 1
        print(f"  ❌ {name} {detail}")
    return condition


# ═══════════════════════════════════════════════════════════════
print("=" * 60)
print("L0: 配置 + 模型")
print("=" * 60)

from src.config import get
check("CONFIG-01 默认值", get("max_refs_total") >= 20, get("max_refs_total"))
threshold = get("min_ref_relevance_score")
check("CONFIG-02 阈值≤0.02", threshold is not None and threshold <= 0.02,
      f"当前={threshold}，>0.02会导致检索全灭！请改 local.secrets.yml")
check("CONFIG-03 缺失键", get("nonexistent_key_xyz_123") is None)
check("CONFIG-04 API Key", bool(get("deepseek_api_key")), "缺少 DEEPSEEK_API_KEY")

from src.models import SectionNode, WritingPlan, Manuscript, ManuscriptSection
sn = SectionNode(section_id="s1", title="测试", bullets=["a", "b"])
d = sn.model_dump()
check("MODEL-01 SectionNode", d["section_id"] == "s1" and len(d["bullets"]) == 2)
wp = WritingPlan(outline=[sn], keywords=["k"], search_queries=["q"])
check("MODEL-02 WritingPlan", len(wp.outline) == 1 and wp.keywords == ["k"])
ms = Manuscript(sections=[ManuscriptSection(section_id="s1", title="t", markdown_body="正文")], version=1)
check("MODEL-03 Manuscript", "正文" in ms.to_markdown())


# ═══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("L1: 检索器 (无 API)")
print("=" * 60)

from src.retriever import _relevance_score, _filter_and_score
from src.models import Reference

ref_md = Reference(
    id="t-md", title="Micro-Doppler Signature Analysis for Moving Target Detection",
    abstract="Time-frequency analysis method for micro-Doppler signatures generated by moving targets.",
    venue="IEEE Trans", year=2023, authors=["Z"], ref_type="J", source="semantic_scholar",
)
ref_quantum = Reference(
    id="t-q", title="Quantum Computing Applications in Cryptography",
    abstract="Quantum key distribution protocols and security guarantees.",
    venue="Nature", year=2023, authors=["X"], ref_type="J", source="crossref",
)
kws = ["微多普勒特征", "动目标检测", "时频分析"]
syn = {"微多普勒特征": ["micro-doppler"], "动目标检测": ["moving target detection"], "时频分析": ["time-frequency"]}

s_no = _relevance_score(ref_md, kws)
s_syn = _relevance_score(ref_md, kws, syn)
check("RET-02 同义词映射生效", s_syn > 0.1 and s_syn > s_no,
      f"无同义词={s_no:.3f} 有同义词={s_syn:.3f}")

s_q = _relevance_score(ref_quantum, kws, syn)
check("RET-03 保底分", abs(s_q - 0.02) < 0.001, f"{s_q:.3f}")

filtered = _filter_and_score([ref_md, ref_quantum], kws, min_score=0.01, synonym_map=syn)
check("RET-04 阈值0.01放行", len(filtered) == 2, f"仅通过{len(filtered)}篇")


# ═══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("L1: 撰写器 (无 API)")
print("=" * 60)

from src.writing.postprocess import _fix_citation_position
from src.writing.revision_engine import _build_term_lockdown_snapshot

r = _fix_citation_position("通过实验验证了可行性。\n[1]\n进一步分析表明")
check("WRIT-01 跨行引用修正", "[1]。" in r or "[1]\n。" in r, repr(r[:80]))

r2 = _fix_citation_position("实验结果如上。[1]")
check("WRIT-02 普通引用修正", "[1]。" in r2 or "结果如上[1]。" in r2, repr(r2[:60]))

spec = {"hardware": {"mcu": {"model": "STC89C52RC"}, "sensors": [{"name": "温湿度", "model": "DHT11"}]}}
snap = _build_term_lockdown_snapshot(spec)
check("WRIT-08 术语锁定快照", "STC89C52RC" in snap and "DHT11" in snap, snap[:200])


# ═══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("L1: 评估器 — 静态规则 (无 API)")
print("=" * 60)

from src.validation.evaluator import _check_thesis_rules
from src.ref_store import ReferenceStore
store = ReferenceStore()

# 场景1：对比语境，不应触发 MCU 误报
ms1 = Manuscript(sections=[
    ManuscriptSection(section_id="abstract_zh", title="摘要",
                      markdown_body="基于STC89C51单片机的温湿度测量与控制系统"),
    ManuscriptSection(section_id="keywords", title="关键词",
                      markdown_body="STC89C51；温湿度；土壤湿度"),
    ManuscriptSection(section_id="s1", title="第1章 引言",
                      markdown_body="本文设计了一种基于STC89C51的温湿度系统。" + "背景"*500),
    ManuscriptSection(section_id="s2", title="第2章 方案对比",
                      markdown_body="本文对比了两种方案：基于ESP32的纯无线方案与基于Arduino的开源方案" + "分析"*500),
    ManuscriptSection(section_id="s3", title="第3章", markdown_body="硬件设计"*600),
    ManuscriptSection(section_id="s4", title="第4章", markdown_body="软件设计"*600),
    ManuscriptSection(section_id="s5", title="第5章", markdown_body="测试"*500),
    ManuscriptSection(section_id="s6", title="第6章 结论", markdown_body="主要工作总结与创新贡献"*200),
], version=1)
p1 = WritingPlan(
    outline=[SectionNode(section_id="s1", title="引言",
                         # 全部为元信息类 bullet，确保 fallback 白名单全部过滤
                         bullets=["本文工作与贡献", "论文结构安排", "章节组织架构"])],
    keywords=["STC89C51", "温湿度", "土壤湿度"], search_queries=["test"],
)
issues = _check_thesis_rules(ms1, p1, store)
mcu_bug = [i for i in issues if i.rule_id == "mcu_abstract_body_mismatch"]
check("EVAL-01 MCU对比不误报", len(mcu_bug) == 0,
      f"误报{mcu_bug[0].message[:100] if mcu_bug else 'none'}")

# 场景2：元信息 bullet 不触发 conclusion_intro_gap 误报
gap_bug = [i for i in issues if i.rule_id == "conclusion_intro_gap"]
check("EVAL-03 结论-引言不误报", len(gap_bug) == 0,
      f"误报{gap_bug[0].message[:100] if gap_bug else 'none'}")


# ═══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("L1: 文献池 — 同义词映射 (需 API)")
print("=" * 60)

from src.ref_store import _build_synonym_map
try:
    syn2 = _build_synonym_map(["微多普勒特征", "时频分析", "目标识别"])
    check("REFS-05 LLM同义词生成", len(syn2) >= 2, f"仅{len(syn2)}键")
except Exception as e:
    check("REFS-05 LLM同义词生成(降级)", True, f"API不可用(可接受): {e}")


# ═══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("L1: 修订产物清洗 + 小节补全 (无 API)")
print("=" * 60)

from src.writing.helpers import _strip_revision_artifacts, _ensure_subsections_present
from src.models import SectionNode as SN

# _strip_revision_artifacts 参数化测试
strip_cases = [
    ("Part 1 [正文]：\n3.1 内容...\nPart 2 [修改日志]：改了一点", "3.1 内容..."),
    ("Part 1：正文\n## 引言\nblah\nPart 2：修改日志", "正文\n## 引言\nblah"),
    ("【正文】\n3.1 内容\n【修改日志】：xxx", "3.1 内容"),
    ("纯正文没有标签", "纯正文没有标签"),
    ("Part 1 正文：\n\n3.1 内容\n\n修订说明：改错字", "3.1 内容"),
    ("Part 1 [正文]\n### 3.2 测试\n正常内容\n\nPart 2 修改日志\n修了bug", "### 3.2 测试\n正常内容"),
    ("Part One [正文]：\n正常文本\n\nPart Two [修改日志]：done", "正常文本"),
]
for i, (inp, exp) in enumerate(strip_cases):
    got = _strip_revision_artifacts(inp)
    check(f"STRIP-0{i+1} {exp[:20]}...", got.strip() == exp.strip(),
          f"got={repr(got[:80])} expected={repr(exp[:80])}")

# _ensure_subsections_present 测试
sn_ensure = SN(
    section_id="s3", title="第3章 硬件设计",
    subsections=[
        SN(section_id="s3_1", title="3.1 总体架构", bullets=["架构图"]),
        SN(section_id="s3_2", title="3.2 核心模块", bullets=["模块划分"]),
        SN(section_id="s3_3", title="3.3 传感器接口", bullets=["接口设计"]),
    ]
)
body_full = "### 3.1 总体架构\n\n系统架构如图3-1所示。\n\n### 3.2 核心模块\n\n模块划分如下。\n\n### 3.3 传感器接口\n\n接口采用SPI协议。"
body_missing = "### 3.1 总体架构\n\n系统架构如图3-1所示。"
body_none = "正文内容没有小节标题"

r_full = _ensure_subsections_present(body_full, sn_ensure)
check("ENSURE-01 齐全不改", "TODO" not in r_full and r_full == body_full,
      f"意外追加了占位符")

r_missing = _ensure_subsections_present(body_missing, sn_ensure)
check("ENSURE-02 补全缺失", "### 3.2 核心模块" in r_missing and "### 3.3 传感器接口" in r_missing,
      f"got={repr(r_missing[-200:])}")
check("ENSURE-02b 可见占位符", "> **待撰写：3.2 核心模块**" in r_missing)

r_none = _ensure_subsections_present(body_none, sn_ensure)
check("ENSURE-03 全缺失补全", "### 3.1" in r_none and "### 3.2" in r_none and "### 3.3" in r_none,
      f"got={repr(r_none[-200:])}")

# _ensure_subsections_present 无 subsections 的章节
sn_empty = SN(section_id="s1", title="引言")
r_empty = _ensure_subsections_present("正文", sn_empty)
check("ENSURE-04 无小节不变", r_empty == "正文", f"got={repr(r_empty)}")

# 模糊匹配：LLM 写了 "4.2 模块实现与部署"，plan 里是 "4.2 模块实现"
sn_fuzzy = SN(
    section_id="s4", title="第4章",
    subsections=[
        SN(section_id="s4_1", title="4.1 总体流程", bullets=[]),
        SN(section_id="s4_2", title="4.2 模块实现", bullets=[]),
    ]
)
body_fuzzy = "### 4.1 总体流程\n\n流程描述。\n\n### 4.2 模块实现与部署\n\n实现详情。"
r_fuzzy = _ensure_subsections_present(body_fuzzy, sn_fuzzy)
check("ENSURE-05 模糊匹配不误补", "> **待撰写：" not in r_fuzzy, f"意外补了占位符: {repr(r_fuzzy)}")

# _align_subsections_titles 测试
from src.writing.helpers import _align_subsections_titles

sn_align = SN(
    section_id="s4", title="第4章",
    subsections=[
        SN(section_id="s4_1", title="4.1 总体流程", bullets=[]),
        SN(section_id="s4_2", title="4.2 模块实现", bullets=[]),
    ]
)
body_align = "### 4.1 总体流程\n\n流程。\n\n### 4.2 模块实现与部署\n\n实现。"
_align_subsections_titles(body_align, sn_align)
check("ALIGN-01 标题对齐", sn_align.subsections[1].title == "4.2 模块实现与部署",
      f"got={sn_align.subsections[1].title}")

# 对齐但 LLM 标题太长不更新
sn_long = SN(
    section_id="s4", title="第4章",
    subsections=[
        SN(section_id="s4_1", title="4.1 流程", bullets=[]),
    ]
)
body_long = "### 4.1 基于深度强化学习的超长描述性标题超过限制字数\n\n内容。"
_align_subsections_titles(body_long, sn_long)
check("ALIGN-02 长标题不对齐", sn_long.subsections[0].title == "4.1 流程",
      f"got={sn_long.subsections[0].title}")

# Manuscript 关键词字段测试
kw_ms = Manuscript(
    sections=[
        ManuscriptSection(section_id="abstract_zh", title="摘要", markdown_body="本文研究了微多普勒特征。"),
        ManuscriptSection(section_id="abstract_en", title="Abstract", markdown_body="This paper studies micro-Doppler."),
    ],
    keywords_zh_text="关键词：微多普勒特征；动目标检测；时频分析",
    keywords_en_text="Keywords: Micro-Doppler; Moving Target Detection; Time-Frequency Analysis",
)
kw_md = kw_ms.to_markdown()
check("KW-01 中文关键词拼接", "关键词：微多普勒特征" in kw_md)
check("KW-02 英文关键词拼接", "Keywords: Micro-Doppler" in kw_md)
check("KW-03 无独立关键词标题", "## 关键词" not in kw_md)

# Manuscript 无关键词字段时不拼接
kw_none = Manuscript(
    sections=[
        ManuscriptSection(section_id="abstract_zh", title="摘要", markdown_body="普通摘要。"),
        ManuscriptSection(section_id="abstract_en", title="Abstract", markdown_body="Plain abstract."),
    ],
)
kw_none_md = kw_none.to_markdown()
check("KW-04 无关键词不拼接", "普通摘要" in kw_none_md and "keywords" not in kw_none_md.lower())


# ═══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("L1: 章标题规范化 (无 API)")
print("=" * 60)

from src.models import _normalize_chapter_title

title_cases = [
    # (section_id, input_title, expected)
    ("s1", "引言", "第1章 引言"),
    ("s1", "第1章 引言", "第1章 引言"),
    ("s3", "系统硬件设计", "第3章 系统硬件设计"),
    ("s3", "第3章 第3章 系统硬件设计", "第3章 系统硬件设计"),
    ("s2", "第2章 现存工作分析与技术综述", "第2章 现存工作分析与技术综述"),
    ("s6", "结论", "第6章 结论"),
    ("s6", "第6章 结论", "第6章 结论"),
    # 非正文章节不处理
    ("abstract_zh", "摘要", "摘要"),
    ("refs", "参考文献", "参考文献"),
    ("acknowledgment", "致谢", "致谢"),
    # 中间含"第2章"不动
    ("s2", "基于第2章技术的综述", "第2章 基于第2章技术的综述"),
]
for i, (sid, inp, exp) in enumerate(title_cases):
    got = _normalize_chapter_title(sid, inp)
    check(f"TITLE-{i+1:02d} {inp} → {exp}", got == exp, f"got={repr(got)}")

# to_markdown 集成测试
t_ms = Manuscript(
    sections=[
        ManuscriptSection(section_id="abstract_zh", title="摘要", markdown_body="摘要内容。"),
        ManuscriptSection(section_id="s1", title="引言", markdown_body="引言正文。"),
        ManuscriptSection(section_id="s2", title="第2章 第2章 相关工作", markdown_body="综述正文。"),
        ManuscriptSection(section_id="s6", title="结论", markdown_body="结论文本。"),
    ],
)
t_md = t_ms.to_markdown()
check("TITLE-INT 输出含第1章", "## 第1章 引言" in t_md)
check("TITLE-INT 输出含第2章", "## 第2章 相关工作" in t_md)
check("TITLE-INT 输出含第6章", "## 第6章 结论" in t_md)
check("TITLE-INT 无重复前缀", "## 第2章 第2章" not in t_md)
check("TITLE-INT 摘要不变", "## 摘要" in t_md)


# ═══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("L1: Body 结构污染清理 (无 API)")
print("=" * 60)

from src.writing.postprocess import _clean_horizontal_rules, _downgrade_body_h1

# _clean_horizontal_rules 测试
hr_body = "一段文字\n\n---\n\n后续内容"
hr_cleaned = _clean_horizontal_rules(hr_body)
check("HR-01 删除隔离水平线", "---" not in hr_cleaned and "一段文字" in hr_cleaned and "后续内容" in hr_cleaned)

hr_table = "| 列A | 列B |\n|---|---|\n| 数据 | 数据 |"
check("HR-02 保留表格分隔", _clean_horizontal_rules(hr_table) == hr_table, f"got={repr(_clean_horizontal_rules(hr_table))}")

# _downgrade_body_h1 测试
h1_body = "# 不应该出现的临时标题\n\n正文内容。\n\n## 正常二级标题\n\n```python\n# 代码块内的注释\nprint('hello')\n```"
h1_result = _downgrade_body_h1(h1_body)
check("H1-01 H1降级为H2", h1_result.startswith("## 不应该出现的临时标题"))
_in_code = False
_bare_h1 = False
for _l in h1_result.split("\n"):
    if _l.strip().startswith("```"):
        _in_code = not _in_code
    elif not _in_code and _l.startswith("# ") and not _l.startswith("## "):
        _bare_h1 = True
        break
check("H1-01b 无裸# 行", not _bare_h1)
check("H1-02 代码块内H1不动", "# 代码块内的注释" in h1_result)
check("H1-03 H2不变", "## 正常二级标题" in h1_result)

# to_markdown H1 标题测试
t2_ms = Manuscript(
    thesis_title="测试论文题目",
    sections=[
        ManuscriptSection(section_id="abstract_zh", title="摘要", markdown_body="测试摘要。"),
        ManuscriptSection(section_id="s1", title="第1章 引言", markdown_body="引言。"),
    ],
)
t2_md = t2_ms.to_markdown()
check("H1-04 to_markdown含H1标题", t2_md.startswith("# 测试论文题目"))
check("H1-05 to_markdown含常规章节", "## 摘要" in t2_md and "## 第1章 引言" in t2_md)

# 无 thesis_title 时不输出 H1
t3_ms = Manuscript(
    sections=[ManuscriptSection(section_id="abstract_zh", title="摘要", markdown_body="测试。")],
)
t3_md = t3_ms.to_markdown()
check("H1-06 无标题不输出H1", not t3_md.startswith("# "), f"got={repr(t3_md[:50])}")


# ═══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("L1: 规划层标题规范化 (无 API)")
print("=" * 60)

from src.planner import _normalize_outline_titles, _clean_top_level_subsections
from src.models import WritingPlan, SectionNode

# _normalize_outline_titles 测试
plan1 = WritingPlan(
    outline=[
        SectionNode(section_id="abstract_zh", title="摘要"),
        SectionNode(section_id="s1", title="引言"),
        SectionNode(section_id="s2", title="文献综述"),
        SectionNode(section_id="s3", title="第3章 第3章 系统设计"),
        SectionNode(section_id="s6", title="结论"),
        SectionNode(section_id="acknowledgment", title="致谢"),
    ],
    keywords=["测试"], search_queries=["test"],
)
_normalize_outline_titles(plan1)
titles = {s.section_id: s.title for s in plan1.outline}
check("PLAN-TITLE-01 s1规范化", titles["s1"] == "第1章 引言", f"got={titles['s1']}")
check("PLAN-TITLE-02 s2规范化", titles["s2"] == "第2章 文献综述", f"got={titles['s2']}")
check("PLAN-TITLE-03 s3去重", titles["s3"] == "第3章 系统设计", f"got={titles['s3']}")
check("PLAN-TITLE-04 s6规范化", titles["s6"] == "第6章 结论", f"got={titles['s6']}")
check("PLAN-TITLE-05 摘要不变", titles["abstract_zh"] == "摘要")
check("PLAN-TITLE-06 致谢不变", titles["acknowledgment"] == "致谢")

# _clean_top_level_subsections 测试
plan2 = WritingPlan(
    outline=[
        SectionNode(section_id="abstract_zh", title="摘要"),
        SectionNode(section_id="s1", title="第1章 引言"),
        SectionNode(section_id="s3", title="第3章 方法"),
        SectionNode(section_id="s3_1", title="3.1 架构"),
        SectionNode(section_id="s3_2", title="3.2 模块"),
        SectionNode(section_id="s4", title="第4章 实现"),
        SectionNode(section_id="s4_1", title="4.1 流程"),
        SectionNode(section_id="acknowledgment", title="致谢"),
    ],
    keywords=["测试"], search_queries=["test"],
)
_clean_top_level_subsections(plan2)
plan2_ids = {s.section_id for s in plan2.outline}
check("PLAN-SUB-01 移除s3_1", "s3_1" not in plan2_ids)
check("PLAN-SUB-02 移除s3_2", "s3_2" not in plan2_ids)
check("PLAN-SUB-03 移除s4_1", "s4_1" not in plan2_ids)
check("PLAN-SUB-04 保留s3", "s3" in plan2_ids)
check("PLAN-SUB-05 节点数正确", len(plan2.outline) == 5, f"got={len(plan2.outline)}")

# 验证迁移：子节应出现在父章节的 subsections 中
s3_node = next(s for s in plan2.outline if s.section_id == "s3")
check("PLAN-SUB-06 s3_1迁入s3", "s3_1" in {ss.section_id for ss in s3_node.subsections})
check("PLAN-SUB-07 s3_2迁入s3", "s3_2" in {ss.section_id for ss in s3_node.subsections})
s4_node = next(s for s in plan2.outline if s.section_id == "s4")
check("PLAN-SUB-08 s4_1迁入s4", "s4_1" in {ss.section_id for ss in s4_node.subsections})

# 迁移时排序正确（s3_1 在 s3_2 前面）
s3_subs_ids = [ss.section_id for ss in s3_node.subsections]
check("PLAN-SUB-09 s3子节排序", s3_subs_ids == ["s3_1", "s3_2"], f"got={s3_subs_ids}")

# 不改变已有 subsections（去重）
plan3 = WritingPlan(
    outline=[
        SectionNode(section_id="s3", title="第3章",
                     subsections=[SectionNode(section_id="s3_1", title="已存在3.1")]),
        SectionNode(section_id="s3_1", title="重复的3.1"),
        SectionNode(section_id="s3_2", title="新3.2"),
    ],
    keywords=["测试"], search_queries=["test"],
)
_clean_top_level_subsections(plan3)
s3b = plan3.outline[0]
check("PLAN-SUB-10 去重不覆盖", s3b.subsections[0].title == "已存在3.1",
      f"got={s3b.subsections[0].title}")
check("PLAN-SUB-11 新节点追加", "s3_2" in {ss.section_id for ss in s3b.subsections})


# ═══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print(f"结果: {'🎉 全部通过' if FAILS == 0 else f'❌ {FAILS} 项失败'}")
print("=" * 60)
sys.exit(0 if FAILS == 0 else 1)
